### ISSUE TITLE
Is the subsets parameter no longer supported?

### ISSUE THREAD

**Issue by ksk-waqs** [nuxt-community/google-fonts-module#23]
Hi, I tried to configure the "subsets" parameter in my project, but found that it did not work. Apparently, Google itself has stopped providing support.

**Comment by kissu** [comment]
Can confirm that any configuration of `subsets` has pretty much 0 effect.
![image](https://user-images.githubusercontent.com/5133074/97246522-d4d7a880-17fd-11eb-8117-2f99f71969bc.png)

**Comment by ricardogobbosouza** [comment]
Hi @ksk-waqs 
**subsets** is part of google fonts [v1](https://developers.google.com/fonts/docs/getting_started#specifying_script_subsets), we are currently using [v2](https://developers.google.com/fonts/docs/css2).
I will fix this soon.

**Comment by ricardogobbosouza** [comment]
Fixed on [v1.1.5](https://github.com/nuxt-community/google-fonts-module/releases/tag/v1.1.5)

**Comment by kissu** [comment]
Just upgraded to `1.1.5`.
Got this error on `nuxt generate`

My config didn't changed and I still totally working on `1.1.3`.
![image](https://user-images.githubusercontent.com/5133074/98607993-93a9c300-22ea-11eb-95f2-6ba6482ba4d3.png)

**Comment by ricardogobbosouza** [comment]
Hi @kissu 
Can share your configuration?

**Comment by kissu** [comment]
Hi, sorry for the late reply.
Here is my config
```js
[
  '@nuxtjs/google-fonts',
  {
    families: {
      Nunito: {
        wght: [400, 600, 700, 800],
      },
    },
    subsets: ['latin'],
    display: 'swap',
    prefetch: false,
    preconnect: false,
    preload: false,
    download: true,
    // base64: true,
  },
]
```

**Comment by ricardogobbosouza** [comment]
@kissu 
Fixed on v1.1.6, sorry for that

**Comment by kissu** [comment]
Hi, seems like the issue is still here, tried with `subsets: ['latin']` and `subsets: 'latin'` but it still gives me
![image](https://user-images.githubusercontent.com/5133074/98737376-6589b900-23a6-11eb-9b13-49a23bfdc484.png)

**Comment by ricardogobbosouza** [comment]
On google itself we have the same result

https://fonts.googleapis.com/css?family=Roboto+Mono
https://fonts.googleapis.com/css?family=Roboto+Mono&subset=greek,cyrillic

**Comment by kissu** [comment]
Ok indeed, it is working properly it's just that our browsers serve us all the subsets.
Nvm so, thanks for your time ! 👍🏻 
https://github.com/google/fonts/issues/1836
